### ISSUE TITLE
Event not sent on k8s cluster

### ISSUE THREAD

**Issue by dinoba** [DataDog/datadog-go#276]
I'm trying to send events using few methods. 

I tried using DD_AGENT_HOST (host port binding) (see dogstatsdClient bellow) . 
I also tried using a Unix Domain Socket (see dogstatsdClientLocal bellow).
No errors, nothing in DD agent logs and also no events on DD. Everything else on cluster works well, k8s events, custom events from Rubby apps...

What am I doing wrong?

```
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/DataDog/datadog-go/v5/statsd"
)

func main() {
	hp := os.Getenv("DD_AGENT_HOST")
	hp = hp + ":8125"
	fmt.Println(hp)
	dogstatsdClient, err := statsd.New(hp)
	if err != nil {
		log.Fatal(err)
	}
	dogstatsdClientLocal, err := statsd.New("127.0.0.1:8125")

	if err != nil {
		log.Fatal(err)
	}
	for {
		fmt.Println("SimpleEvent")
		dogstatsdClient.SimpleEvent("Dino simple event title", "Dino simple event text")
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println("Event()")
		e := NewEvent("dino event title", "dino event yxy", "dino_aggreggation")
		dogstatsdClient.Event(e)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println("FLUSH")
		dogstatsdClient.Flush()

		fmt.Println("TRY LOCAL")
		dogstatsdClientLocal.SimpleEvent("Dino simple event title", "Dino simple event text")
		if err != nil {
			fmt.Println(err)
		}
		e = NewEvent("dino event title", "dino event yxy", "dino_aggreggation")
		dogstatsdClientLocal.Event(e)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println("FLUSH LOCAL")
		dogstatsdClientLocal.Flush()

		time.Sleep(10 * time.Second)
	}
}

func NewEvent(title, text, aggregationKey string) *statsd.Event {
	return &statsd.Event{
		Title:          title,
		Text:           text,
		AggregationKey: aggregationKey,
		AlertType:      statsd.Warning,
	}
}

```

this is my deploy file

```

kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-ddclient
  labels:
    app:  test-ddclient
    tags.datadoghq.com/env: "production"
    tags.datadoghq.com/service: "test-ddclient"
spec:
  selector:
    matchLabels:
      app: test-ddclient
  template:
    metadata:
      labels:
        app: test-ddclient
        tags.datadoghq.com/env: "production"
        tags.datadoghq.com/service: "test-ddclient"
    spec:
      containers:
        - name: testddclient

          image: docker.io/********/ddclient
          imagePullPolicy: Always
          volumeMounts:
          - name: dsdsocket
            mountPath: /var/run/datadog
          env:
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_TRACE
              value: "true"
            - name: DD_TRACE_STARTUP_LOGS
              value: "true"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_STATSD_TRANSPORT
              value: "UDS"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_APM_ENV
              value: production
            - name: DD_TRACE_AGENT_URL
              value: 'unix:///var/run/datadog/apm.socket'
      volumes:
      - name: dsdsocket
        hostPath:
          path: /var/run/datadog/
```
